server:
  port: 8193

coinlayer.exchange-rate:
  access-key: 49631900db01ffefd3a8227c3fc64b4d
  latest: http://api.coinlayer.com/api/live
  historical: http://api.coinlayer.com/api/


spring:
  kafka:
    bootstrap-servers: kafka:29092
    exchange:
      rate:
        topic:
          latest: exchange_rate_latest
          historic: exchange_rate_historic

cron:
  job:
    exchange:
      rate:
        historic: 0 0 3 * * ?    # runs at 3 AM every day

management:
  endpoints:
    web:
      exposure:
        include: ["info","metrics","health","env","refresh"]


  endpoint:
    env:
      post:
        enabled: true

